name: Merge Into Main

on:
  pull_request:
    branches: ["main"]

jobs:
    merge:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
    
            - name: Check if the branch was checked out from Main
              run: 
                branch_name=$(echo $GITHUB_REF | cut -d / -f 3)
                if [ "$branch_name" == "main" ]; then
                  echo "The branch was created from main."
                  git checkout main
                  git merge $GITHUB_REF
                  git push
                else
                  echo "The branch was not created from main."
                fi

            - name: Upload a comment to the pull request
              uses: actions/github-comment@v1
              with:
                message: "The pull request has been merged into main."
                branch: $GITHUB_REF
